version: "3"
services:
  db:
    image: mariadb:10.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      # MARIADB_ROOT_PASSWORD: 
      # MARIADB_ROOT_PASSWORD_HASH: 
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      # MARIADB_RANDOM_ROOT_PASSWORD:
    ports:
      - 3306:3306
  # service:
  #   build: .
  #   ports:
  #     - 80:80
  #   stdin_open: true
  #   tty: true       
